version: '3'

services:
   broker:
     container_name: fhem_mqtt
     restart: unless-stopped
     image: eclipse-mosquitto:latest
     volumes:
       - "./mosquitto:/mosquitto"
       - "/etc/localtime:/etc/localtime:ro"
     networks:
       - fhem-network
     ports:
       - "1883:1883"
     environment:
      - TZ=Europe/Berlin

   tasmotaadmin:
    container_name: fhem_tasmotaadmin
    restart: unless-stopped
    image: raymondmm/tasmoadmin:latest
    volumes:
      - ./tasmotaadmin/data:/data
        #- "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    ports:
      - "8081:80"
    networks:
      - fhem-network


   tasmocompiler:
    container_name: fhem_tasmotacompiler
    restart: unless-stopped
    image: benzino77/tasmocompiler:latest
    ports:
      - "8082:3000"
    networks:
      - fhem-network


   fhem:
     container_name: fhem_fhem
     image: fhem/fhem:latest
     restart: unless-stopped
     depends_on:
        - broker

     #devices:
     # -{usbport}:/dev/usb1
     # - "/dev/ttyAMA0:/dev/ttyAMA0"
     # - "/dev/ttyUSB0:/dev/ttyUSB0"
     # dns: 192.168.1.107
     # dns_search: fritz.box
     networks:
       - fhem-network
     ports:
       #- "8083:8083"
       #- "7072:7072"
       - "222:22"
     volumes:
       - "/etc/localtime:/etc/localtime:ro"
         #- "/etc/timezone:/etc/timezone:ro"
       - "./fhem/:/opt/fhem/"
       - "./pre-init.sh:/docker/pre-init.sh"
       - "./post-init.sh:/docker/post-init.sh"
       - "./pre-start.sh:/docker/pre-start.sh"
       - "./post-start.sh:/docker/post-start.sh"
     environment:
       #FHEM_UID: 6061
       #FHEM_GID: 6061
       FHEM_UID: 1000
       FHEM_GID: 1000
       FHEM_PERM_DIR: 0770
       FHEM_PERM_FILE: 0660
       LOGFILE: "./log/fhem-%Y-%m.log"
       UMASK: 0037
       BLUETOOTH_GID: 6001
       GPIO_GID: 6002
       I2C_GID: 6003
       # Shutdown timeout
       TIMEOUT: 10
       RESTART: 1
       TELNETPORT: 7072
       TZ: Europe/Berlin
       APT_PKGS: "cvs ranger zsh socat rlwrap htop tmux vim"
       #CPAN_PKGS: ""
       #PIP_PKGS: ""
       #NPM_PKGS: ""
       # CONFIGTYPE: configDB
       # CONFIGTYPE=fhem.cfg.demo
     links:
        - broker


   portainer:
     container_name: fhem_portainer
     image: portainer/portainer:latest
     restart: unless-stopped
     depends_on:
        - fhem
     command: -H unix:///var/run/docker.sock --no-auth
     ports:
         - "9000:9000"
     environment:
         - TZ=Europe/Berlin
         - REGISTRY_HTTP_TLS_CERTIFICATE=/certs/portainer.crt
         - REGISTRY_HTTP_TLS_KEY=/certs/portainer.key
     volumes:
       - "/etc/localtime:/etc/localtime:ro"
         #- "/etc/timezone:/etc/timezone:ro"
       - "/var/run/docker.sock:/var/run/docker.sock"
       - "portainer_data:/data"
       - "/home/pirate/certs/portainer.key:/certs/portainer.key"
       - "/home/pirate/certs/portainer.crt:/certs/portainer.crt"
     networks:
         - fhem-network

   adminer:
     container_name: fhem_adminer
     image: adminer:latest
     restart: unless-stopped
     depends_on:
       - fhem
     environment:
       - TZ=Europe/Berlin
     volumes:
       - "/etc/localtime:/etc/localtime:ro"
         #       - "/etc/timezone:/etc/timezone:ro"
     ports:
       - 9090:8080
     networks:
       - fhem-network


   homebridge:
     container_name: fhem_homebridge
     image: oznu/homebridge:latest
     restart: unless-stopped
     environment:
      - TZ=Europe/Berlin
      - PUID=1000
      - PGID=1000
     depends_on:
      - reverseproxy
     network_mode: host
     environment:
      - TZ=Europe/Berlin
      - PGID=1000
      - PUID=1000
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_CONFIG_UI_PORT=8080
     volumes:
       - "./homebridge:/homebridge"

   reverseproxy:
     container_name: fhem_nginx
     restart: unless-stopped
     image: nginx:latest
     environment:
      - TZ=Europe/Berlin
      - PGID=1000
      - PUID=1000
     volumes:
        - ./reverseproxy/config/nginx.conf:/etc/nginx/nginx.conf
        - ./reverseproxy/config/.htpasswd:/etc/nginx/.htpasswd
        - ./reverseproxy/config/cert.key:/etc/nginx/cert.key
        - ./reverseproxy/config/cert.crt:/etc/nginx/cert.crt
     ports:
         - 80:80
         - 443:443
     networks:
         - fhem-network
     depends_on:
        - fhem

   deconz:
     image: marthoc/deconz
     container_name: fhem_deconz
     network_mode: host
     restart: unless-stopped
     volumes:
       - ./deconz/root/:/root/.local/share/dresden-elektronik/deCONZ
       - ./deconz/otau/:/root/otau
         #     devices:
         #       - /dev/ttyACM0
     environment:
       - TZ=Europe/Berlin
       - DECONZ_DEVICE=/dev/ttyACM0
       - DECONZ_WEB_PORT=8090
       - DECONZ_WS_PORT=8443
       - DEBUG_INFO=1
       - DEBUG_APS=0
       - DEBUG_ZCL=0
       - DEBUG_ZDP=0
       - DEBUG_OTAU=0
         #- DECONZ_VNC_PORT=5900
         #- DECONZ_VNC_MODE=1
         #- DECONZ_VNC_PASSWORD=changeme
       - DECONZ_UPNP=1
   watchtower:
    image: containrrr/watchtower
    container_name: fhem_watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
     #- /root/.docker/config.json:/config.json
     #command: --interval 1 watchtower eclipse-mosquitto tasmoadmin tasmocompiler fhem portainer adminer homebridge nginx deconz
    command: --interval 60
    environment:
      - TZ='Europe/Berlin'
     #- REPO_USER='githubuser'
     #- REPO_PASS='password'
     #- WATCHTOWER_NOTIFICATIONS=email
     #- WATCHTOWER_NOTIFICATION_EMAIL_FROM=server@Domain.tld
     #- WATCHTOWER_NOTIFICATION_EMAIL_TO=mail@domain.tld
     #- WATCHTOWER_NOTIFICATION_EMAIL_SERVER=mail.domain.tld
     #- WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=mail@domain.tld
     #- WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=Secret
    restart: unless-stopped

volumes:
  portainer_data:

networks:
  fhem-network:
    driver: bridge
